site_name: "cookie-doh"
repo_url: https://github.com/microsoft/cookie-doh
repo_name: "cookie-doh"
docs_dir: docs
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - search.suggest
extra_css:
  - css/extra.css
# removed because of codeql detection
# https://github.com/microsoft/cookie-doh/security/code-scanning/3
# https://github.com/microsoft/cookie-doh/security/code-scanning/4
#extra_javascript:
#  - js/mathjax.js
#  - js/tex-mml-chtml.js
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_inheritance_diagram: true
            show_if_no_docstring: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_signature_annotations: true
            show_submodules: true
            show_source: true
            group_by_category: false
            show_category_heading: true
            docstring_options:
              ignore_init_summary: false
              merge_init_into_class: true
              separate_signature: true
  - awesome-pages
  - mkdocs-video:
      is_video: true
      video_controls: true
markdown_extensions:
  # Allows for nicely styled notes and warnings: !!! note
  - admonition
  # Allows for adding attributes to markdown content: !(some-image){: align=left }
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - def_list # definition / description lists
  - pymdownx.tasklist: # Allows us to make a Tasklist: [x] some checked thing
      custom_checkbox: true
  # removed because of codeql detection
  # https://github.com/microsoft/cookie-doh/security/code-scanning/3
  # https://github.com/microsoft/cookie-doh/security/code-scanning/4
  #  - pymdownx.arithmatex:
  #      generic: true
copyright: |
  <div id="left_copyright"><span style="color: grey;">Made with <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a></div>
  <div id="center_copyright"><a href="https://go.microsoft.com/fwlink/?LinkId=521839">Privacy & Cookies</a> | <a href="https://go.microsoft.com/fwlink/?linkid=2259814">Consumer Health Privacy</a> | <a href="https://www.microsoft.com/trademarks">Trademarks</a> | <a href="https://go.microsoft.com/fwlink/?LinkID=206977">Terms of use</a> | © 2024 Microsoft</div>
extra:
  generator: false
