[tool.poetry]
name = "cookie-doh"
version = "0.0.14"
description = ""
authors = ["microsoft"]
license = "MIT License"
readme = "README.md"
packages = [{ include = "cookie", from = "src" }]

[tool.poetry.dependencies]
# write here dependencies of your project
python = "^3.10"

[tool.poetry.group.dev.dependencies]
codespell = "*"
coverage = "*"
ipykernel = "*"
ruff = "*"
pyright = "*"
pytest = "*"

[tool.poetry.group.docs.dependencies]
mkdocs = "*"
mkdocs-awesome-pages-plugin = "*"
mkdocs-git-revision-date-localized-plugin = "*"
mkdocs-material = "*"
mkdocs-video = "*"
mkdocstrings = "*"
mkdocstrings-python = "*"
pymdown-extensions = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
