[tool.poetry]
name = "{{project_name}}"
version = "0.0.0"
description = ""
authors = ["microsoft"]
license = "MIT License"
readme = "README.md"
packages = [{ include = "{{module_name}}", from = "src/python" }]

[tool.poetry.dependencies]
# write here dependencies of your project
python = "^3.10"

[tool.poetry.group.dev.dependencies]
coverage = "^7.5.1"
ipykernel = "^6.29.2"
ruff = "^0.4.3"
pyright = "^1.1.349"
pytest = "^8.0.0"

[tool.poetry.group.docs.dependencies]
mdx-truly-sane-lists = "*"
mkdocs = "*"
mkdocs-awesome-pages-plugin = "*"
mkdocs-material = "*"
mkdocs-video = "*"
pymdown-extensions = ">=10.0.0"   # Fix CVE-2023-32309 pymdown-extensions 9.10
sphinx = "*"
sphinx-autodoc-typehints = "*"
sphinx-markdown-builder = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
