name: build-wheels

on:
  workflow_call:

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    name: build-wheels
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U poetry

      - name: build-wheel
        run: |
          poetry build -f wheel

      - name: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: "dist/*.whl"
