name: CI
on:
  push:
    branches: [ main ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: pre-commit
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U pre-commit
          pre-commit install --install-hooks

      - name: pre-commit
        run: |
          pre-commit run --all-files
        env:
          SKIP: "ruff,ruff-format,pyright"

  run-tests:
    runs-on: ubuntu-latest
    name: run-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U poetry
          poetry install

      - name: ruff-check
        run: |
          poetry run ruff check --no-fix --output-format=github

      - name: ruff-format
        run: |
          poetry run ruff format --check

      - name: pyright
        run: |
          poetry run pyright

      - name: pytest
        run: |
          poetry run coverage run -m pytest

      - name: coverage
        run: |
          poetry run coverage xml -o .tmp/reports/coverage.xml

  build-docs:
    runs-on: ubuntu-latest
    name: build-docs
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U poetry
          poetry install

      - name: build-docs
        run: |
          bin/build-docs

      - name: upload-gh-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/site

  deploy-docs:
    needs: [run-tests, build-docs, pre-commit]
    runs-on: ubuntu-latest
    name: deploy-docs
    permissions:
      pages: write
      id-token: write
    if: github.ref_name == 'main'
    steps:
      - name: deploy-gh-pages
        id: deployment
        uses: actions/deploy-pages@v4

  codeql:
    uses: ./.github/workflows/codeql.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      security-events: write
