name: copier

on:
  workflow_call:

jobs:
  copier:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        precommit: [true, false]
        documentation: [true, false]
        commitizen: [true, false]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-python-uv

      - name: Install Copier
        run: uv tool install copier

      - name: Run Copier Template
        run: |
          copier copy . .tmp/generated-template \
            --defaults \
            -d organization="microsoft" \
            -d project_name="cookie-doh" \
            -d module_name="cookie" \
            -d cli="doh" \
            -d flash_attn="${{ matrix.flash_attn }}" \
            -d precommit="${{ matrix.precommit }}" \
            -d documentation="${{ matrix.documentation }}" \
            -d commitizen="${{ matrix.commitizen }}"

      - name: Verify Generated Template
        run: |
          cd .tmp/generated-template
          ls -la
          git init -q
          git add -A
          if ${{ matrix.precommit }}; then
            SKIP=pinact uvx pre-commit run --all-files
          fi
          uvx ruff check --exit-non-zero-on-fix
          uvx ruff format --exit-non-zero-on-format
          uvx codespell
