name: copier

on:
  workflow_call:

jobs:
  copier:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        precommit: [true, false]
        documentation: [true, false]
        commitizen: [true, false]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version: "0.11"

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"

      - name: Install Copier
        run: uv tool install copier

      - name: Run Copier Template
        run: |
          copier copy . .tmp/generated-template \
            --defaults \
            -d organization="microsoft" \
            -d project_name="cookie-doh" \
            -d module_name="cookie" \
            -d cli="doh" \
            -d flash_attn="${{ matrix.flash_attn }}" \
            -d precommit="${{ matrix.precommit }}" \
            -d documentation="${{ matrix.documentation }}" \
            -d commitizen="${{ matrix.commitizen }}"

      - name: Verify Generated Template
        run: |
          cd .tmp/generated-template
          ls -la
          git init -q
          git add -A
          if ${{ matrix.precommit }}; then
            SKIP=pinact uvx pre-commit run --all-files
          fi
          uvx ruff check --exit-non-zero-on-fix
          uvx ruff format --exit-non-zero-on-format
          uvx codespell
