name: pr

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-root:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install tmux
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux

          echo $USER

  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  run-tests:
    uses: ./.github/workflows/run-tests.yml

  build-docs:
    uses: ./.github/workflows/build-docs.yml

  codeql:
    uses: ./.github/workflows/codeql.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      security-events: write
