name: pr

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  precommit:
    uses: ./.github/workflows/precommit.yml

  tests:
    uses: ./.github/workflows/tests.yml

  docs:
    uses: ./.github/workflows/docs.yml

  wheels:
    uses: ./.github/workflows/wheels.yml

  codeql:
    uses: ./.github/workflows/codeql.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      security-events: write
