
name: pre-commit

on:
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: pre-commit
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: pre-commit
        run: uvx --with pre-commit-uv -- pre-commit run --all-files
        env:
          SKIP: "ruff,ruff-format,pyright,codespell"
