name: pre-commit

on:
  workflow_call:

jobs:
  precommit:
    runs-on: ubuntu-latest
    name: precommit
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"

      - name: pre-commit
        run: uvx --with pre-commit-uv -- pre-commit run --all-files
        env:
          SKIP: "ruff,ruff-format,pyright,codespell"
