
name: pre-commit

on:
  workflow_call:

jobs:
  precommit:
    runs-on: ubuntu-latest
    name: precommit
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.0"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: pre-commit
        run: uvx --with pre-commit-uv -- pre-commit run --all-files
        env:
          SKIP: "ruff,ruff-format,pyright,codespell"
