name: run-tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run-tests
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: ruff-check
        run: |
          uv run ruff check --no-fix --output-format=github

      - name: ruff-format
        run: |
          uv run ruff format --check

      - name: pyright
        run: |
          uv run pyright

      - name: codespell
        run: |
          uv run codespell

      - name: pytest
        run: |
          uv run coverage run -m pytest

      - name: coverage
        run: |
          uv run coverage xml -o .tmp/reports/coverage.xml
