name: run-tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U pdm
          pdm install

      - name: ruff-check
        run: |
          pdm run ruff check --no-fix --output-format=github

      - name: ruff-format
        run: |
          pdm run ruff format --check

      - name: pyright
        run: |
          pdm run pyright

      - name: codespell
        run: |
          pdm run codespell

      - name: pytest
        run: |
          pdm run coverage run -m pytest

      - name: coverage
        run: |
          pdm run coverage xml -o .tmp/reports/coverage.xml
