name: run-tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run-tests
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@f98e06938123ccabd21905ea5d0069192241f9f1 # v8.3.1

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          uv sync --no-group docs
        env:
          UV_LINK_MODE: copy

      - name: ruff-check
        run: |
          uv run --no-sync ruff check --no-fix --output-format=github

      - name: ruff-format
        run: |
          uv run --no-sync ruff format --check

      - name: pyright
        run: |
          uv run --no-sync pyright

      - name: codespell
        run: |
          uv run --no-sync codespell

      - name: pytest
        run: |
          uv run --no-sync pytest
