name: weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '42 23 * * 4'

jobs:
  codeql:
    uses: ./.github/workflows/codeql.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      security-events: write
