name: wheels

on:
  workflow_call:

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    name: build-wheels
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U pdm

      - name: build-wheel
        run: |
          pdm build

      - name: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: "dist/*.whl"

  # publish-wheels:
  #   needs: [build-wheels]
  #   runs-on: ubuntu-latest
  #   name: publish-wheels
  #   if: github.ref_name == 'main'
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/cookie-doh
  #   permissions:
  #     id-token: write
  #   steps:
  #     - name: download-wheels
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: wheels
  #         path: dist/

  #     - name: publish-wheels
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         user: __token__
  #         password: ${{ secrets.PYPI_API_TOKEN }}
